[features]
seeds = false
skip-lint = false

[programs.localnet]
defai_swap = "5ag9ncKTGrhDxdfvRxmSenP848kkgP6BMdaTFLfa2siT"
defai_staking = "DtTDbmQgghWJYp3F4vhaaJGyGoF86qRZh9t2kMtmPBbg"
defai_estate = "DYXXvied9wwpDaE1NcVS56BfeQ4ZxXozft7FCLNVUG41"
defai_app_factory = "7NF6yiQeRbNpYZJzgdijQErD1WYh9mUxwN5SBDpSA6dX"

[programs.devnet]
defai_swap = "EMwWSFW7rxS3Jh3CAsGYNwiYX6myucnFqFxTezBtaEvy"
defai_staking = "3f1FBXvybT9m6ppRkqPyQBQ318KrC2fU3NHVUtnfNJyv"
defai_estate = "BUUhKqR35SGMgE9KALrYHTsCuNGGQcce8h54sfGGUGm1"
defai_app_factory = "62javQ376d4hShFrQQfts6kvEBzHKmSWSxPA3xyxxmLM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000
skip_local_validator = true

[workspace]
members = ["defai_swap", "defai_staking", "defai_estate", "defai_app_factory"]
types = "target/types"